# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running pre/post install scripts (if any issues)
RUN npm install --ignore-scripts

# Copy tsconfig and src folder
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

# Expose port if needed, but MCP uses stdio typically.

# Command to run the server
CMD [ "npm", "start" ]
