# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:18-slim AS builder

WORKDIR /app
# Install build dependencies for sharp
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
  && rm -rf /var/lib/apt/lists/*

# Copy source files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm ci \
  && npm run build

# Runtime stage
FROM node:18-slim
WORKDIR /app

# Install runtime dependency for sharp
RUN apt-get update && apt-get install -y \
    libvips-dev \
  && rm -rf /var/lib/apt/lists/*

# Copy package files and install prod deps without scripts
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# Copy built files
COPY --from=builder /app/dist ./dist

# Set allowed directory environment variable
ENV ALLOWED_DIRECTORY=/app

# Start command
CMD ["node", "dist/index.js"]
